# Classification using Tensorflow

In [65]:
# importing packages

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)
import numpy as np
import matplotlib.pyplot as plt

In [66]:
# importing data-set

data = pd.read_csv('iris.csv')

In [67]:
# display of data

data[1:20]

sepal_length  sepal_width  petal_length  petal_width species
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa

In [68]:
# Creating features and target attribute

X_features=['sepal_length','sepal_width','petal_length','petal_width']
Y_label=['species']

In [69]:
# Creting features and target matrix and one-hot encoding

X=data[X_features]
Y=data[Y_label]

encoder=LabelEncoder()
y1=encoder.fit_transform(Y)
Y=pd.get_dummies(y1).values

C:\Users\NITESH\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [70]:
## One-hot encoder assignment

# sentosa=[1,0,0]
# versicolor = [0,1,0]
# verginica = [0,0,1]

# Display
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [71]:
# Train , test split using sklearn

train_X, test_X, train_Y, test_Y=train_test_split(X,Y, test_size=0.2, random_state=0)

In [72]:
# Layers creating using keras

l0 = tf.keras.layers.Dense(units=4, input_shape=(4,), activation='relu')
l1 = tf.keras.layers.Dense(units=3, activation='softmax')
model = tf.keras.Sequential([l0,l1])

In [73]:
# Model compiling

model.compile(tf.keras.optimizers.Adam(0.02), loss='categorical_crossentropy', metrics=['accuracy'])

In [74]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [75]:
# Fitting model using 100 iterations

model.fit(train_X, train_Y, epochs=100)

Epoch 1/100
120/120 [==============================] - 0s 2ms/step - loss: 2.3960 - acc: 0.0333
Epoch 2/100
120/120 [==============================] - 0s 67us/step - loss: 1.5401 - acc: 0.0167
Epoch 3/100
120/120 [==============================] - 0s 67us/step - loss: 1.0820 - acc: 0.3167
Epoch 4/100
120/120 [==============================] - 0s 100us/step - loss: 0.9752 - acc: 0.4333
Epoch 5/100
120/120 [==============================] - 0s 67us/step - loss: 0.8978 - acc: 0.5250
Epoch 6/100
120/120 [==============================] - 0s 100us/step - loss: 0.8179 - acc: 0.5750
Epoch 7/100
120/120 [==============================] - 0s 100us/step - loss: 0.7225 - acc: 0.6083
Epoch 8/100
120/120 [==============================] - 0s 66us/step - loss: 0.6806 - acc: 0.6917
Epoch 9/100
120/120 [==============================] - 0s 67us/step - loss: 0.6725 - acc: 0.6917
Epoch 10/100
120/120 [==============================] - 0s 100us/step - loss: 0.6008 - acc: 0.7167
Epoch 11/100
120/120 [====

120/120 [==============================] - 0s 33us/step - loss: 0.0845 - acc: 0.9750
Epoch 85/100
120/120 [==============================] - 0s 67us/step - loss: 0.0820 - acc: 0.9833
Epoch 86/100
120/120 [==============================] - 0s 67us/step - loss: 0.0812 - acc: 0.9750
Epoch 87/100
120/120 [==============================] - 0s 67us/step - loss: 0.0781 - acc: 0.9750
Epoch 88/100
120/120 [==============================] - 0s 33us/step - loss: 0.0811 - acc: 0.9750
Epoch 89/100
120/120 [==============================] - 0s 67us/step - loss: 0.0857 - acc: 0.9750
Epoch 90/100
120/120 [==============================] - 0s 67us/step - loss: 0.0809 - acc: 0.9750
Epoch 91/100
120/120 [==============================] - 0s 67us/step - loss: 0.0806 - acc: 0.9750
Epoch 92/100
120/120 [==============================] - ETA: 0s - loss: 0.0715 - acc: 0.968 - 0s 86us/step - loss: 0.0766 - acc: 0.9750
Epoch 93/100
120/120 [==============================] - 0s 57us/step - loss: 0.0839 - acc: 0.

In [76]:
# Storing test predictions
test_pred=model.predict(test_X)
test_pred

array([[7.00710174e-08, 7.96912052e-03, 9.92030859e-01],
       [9.54307988e-03, 9.89500105e-01, 9.56788834e-04],
       [9.99224782e-01, 7.75153399e-04, 1.05342430e-16],
       [4.95763501e-08, 1.58698224e-02, 9.84130144e-01],
       [9.96287704e-01, 3.71226855e-03, 4.18721623e-14],
       [4.88137530e-09, 3.13122454e-03, 9.96868789e-01],
       [9.97656226e-01, 2.34371983e-03, 1.30556009e-14],
       [9.06299741e-04, 9.91208076e-01, 7.88560417e-03],
       [8.50776851e-04, 9.87960458e-01, 1.11887185e-02],
       [6.36944687e-03, 9.92707551e-01, 9.23049229e-04],
       [8.85328859e-07, 5.74265458e-02, 9.42572534e-01],
       [1.20756018e-03, 9.92921770e-01, 5.87064866e-03],
       [7.19734642e-04, 9.78510618e-01, 2.07696520e-02],
       [7.90195423e-04, 9.78851318e-01, 2.03585215e-02],
       [4.05659899e-04, 9.44659889e-01, 5.49345389e-02],
       [9.96202052e-01, 3.79795232e-03, 7.15305365e-14],
       [5.23321505e-04, 9.49018836e-01, 5.04578054e-02],
       [6.96786621e-04, 9.44120

In [77]:
# Creting list of original class and predicted class

y_test_class=np.argmax(test_Y, axis=1)
y_pred_class=np.argmax(test_pred, axis=1)

In [81]:
# Classification report and Confusion matrix

print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

   micro avg       1.00      1.00      1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
